---
- name: Attaching policy to role vmimport
  hosts: localhost
  connection: local
  vars_files:
  - [var.yml]
  tasks:
  - name: assigning policy to role vmimport
    iam_policy:
     iam_type: role
     iam_name: vmimport
     state: present
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}" 
     policy_document: role-policy.json 
     policy_name: vmimport
    
 
